env:
  CIRRUS_CLONE_DEPTH: 1
  ARCH: amd64

task:
  timeout_in: 120m
  freebsd_instance:
    matrix:
#      image: freebsd-13-0-current-amd64-v20190117
      image: freebsd-12-0-release-amd64
#      image: freebsd-11-2-release-amd64
    cpu: 8
    memory: 16G
  install_script:
    - sed -i.bak -e 's,pkg+http://pkg.FreeBSD.org/\${ABI}/quarterly,pkg+http://pkg.FreeBSD.org/\${ABI}/latest,' /etc/pkg/FreeBSD.conf
    #- pkg upgrade -y
    - pkg install -y poudriere git
  script:
    - ./porttest.sh
