# $FreeBSD: head/emulators/virtualbox-ose-additions-nox11/Makefile 501807 2019-05-16 22:16:06Z jkim $

PKGNAMESUFFIX=	-additions-nox11

OPTIONS_EXCLUDE=	DBUS DEBUG OPENGL X11

MASTERDIR=	${.CURDIR}/../virtualbox-ose-additions

.include "${MASTERDIR}/Makefile"
